# Generated by Django 4.0.5 on 2022-06-28 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataset', '0002_destination_origin_receiver_shipper_courier_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('shipment_no', models.CharField(default=shipment.models.shipment_no_generate, max_length=100, primary_key=True, serialize=False)),
                ('shipper_account', models.CharField(max_length=100)),
                ('shipper_address', models.CharField(max_length=200)),
                ('shipper_city', models.CharField(max_length=200)),
                ('shipper_state', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_zip', models.CharField(max_length=20)),
                ('shipper_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipper_mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_address', models.CharField(max_length=200)),
                ('receiver_city', models.CharField(max_length=200)),
                ('receiver_state', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_zip', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=200, null=True)),
                ('awb_no', models.CharField(blank=True, max_length=200, null=True)),
                ('piece', models.IntegerField(blank=True, default=1, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('content', models.CharField(choices=[('Sample', 'Sample'), ('Document', 'Document'), ('Envelope', 'Envelope')], default='Sample', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pickup_by', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD'), ('EURO', 'EURO')], default='BDT', max_length=20)),
                ('prepaid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('collect_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('third_party_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=200, null=True)),
                ('account_no', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.courier')),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.destination')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.origin')),
                ('receiver_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.receiver')),
                ('shipper_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.shipper')),
            ],
        ),
    ]
