# Generated by Django 4.0.5 on 2022-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
