# Generated by Django 4.0.5 on 2022-10-31 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataset', '0002_destination_origin_receiver_shipper_courier_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sender_attention', models.CharField(max_length=100)),
                ('sender_company', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_city', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_phone', models.CharField(max_length=100)),
                ('sender_email', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_nid', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_attention', models.CharField(max_length=100)),
                ('receiver_company', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_zip', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=100)),
                ('receiver_email', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_nid', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Collect', 'Collect')], default='Prepaid', max_length=20)),
                ('ship_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('piece', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('product_value', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(choices=[('Sample', 'Sample'), ('Document', 'Document'), ('Envelope', 'Envelope')], default='Sample', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('receiver_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.destination')),
                ('sender_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.origin')),
            ],
        ),
    ]
