# Generated by Django 4.0.5 on 2023-01-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_slider_alter_about_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='service')),
                ('icon', models.ImageField(blank=True, upload_to='service')),
                ('point1', models.CharField(max_length=100)),
                ('point2', models.CharField(max_length=100)),
                ('point3', models.CharField(max_length=100)),
            ],
        ),
    ]
