# Generated by Django 4.0.5 on 2023-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_cargoservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
