# Generated by Django 4.0.5 on 2022-06-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesparent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesparent',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('shipper_code', models.CharField(default=sales.models.shipper_code, max_length=20, primary_key=True, serialize=False)),
                ('shipper_company', models.CharField(max_length=100)),
                ('shipper_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salesparent',
            name='shipper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.shipper'),
            preserve_default=False,
        ),
    ]
