# Generated by Django 4.0.5 on 2022-06-28 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesparent_mobile_salesparent_street_shipper_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipper',
            old_name='email',
            new_name='shipper_name',
        ),
        migrations.AddField(
            model_name='salesparent',
            name='city',
            field=models.CharField(default=datetime.date.today, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesparent',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesparent',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesparent',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesparent',
            name='zip',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='zip',
            field=models.CharField(default=233, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesparent',
            name='street',
            field=models.CharField(default=datetime.date.today, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipper',
            name='shipper_address',
            field=models.CharField(max_length=200),
        ),
    ]
